### ISSUE TITLE
If not give height and width value CircleFloatingMenu buttons doesnt work.

### ISSUE THREAD

**Issue by kalismeras61** [yumi0629/FlutterUI#1]
Hello, when i removed Posioned Widget height and width value buttons onTap event doesnt work.

**Comment by yumi0629** [comment]
> Hello, when i removed Posioned Widget height and width value buttons onTap event doesnt work.

Which widget do you mean?

**Comment by kalismeras61** [comment]
> > Hello, when i removed Posioned Widget height and width value buttons onTap event doesnt work.
> 
> Which widget do you mean?

CircleFloatingMenu

**Comment by yumi0629** [comment]
> CircleFloatingMenu

Sorry, in my demo, if you don't give a certain width/height or direction constraints to Posioned, Posioned's defalut width and height are both infinity. This will make GestureDetector's onTap() callback invalid. 
This is because I give the sub menus translate transforms, which will cause some problems. If sub menus's parent is not big enough or has infinity constraints, this will make the translated sub menu can not response to the click event. Same as this issue: [GestureDetector fails if its child is transformed](https://github.com/flutter/flutter/issues/6606).
This repository is just my study notebook, some functions are not completed. Temporarily, I don't know how to fix this bug, I feel so sorry.
